/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TripDetailRouteImport } from './routes/trip-detail'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminTripsRouteImport } from './routes/admin.trips'
import { Route as ApiBookingRouteImport } from './routes/api/booking'
import { Route as ApiEnquiriesRouteImport } from './routes/api/enquiries'
import { Route as ApiMyBookingsRouteImport } from './routes/api/my-bookings'
import { Route as ApiTripsRouteImport } from './routes/api/trips'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as AdminTripsIndexRouteImport } from './routes/admin.trips.index'
import { Route as AdminTripsNewRouteImport } from './routes/admin.trips.new'
import { Route as ApiAdminBookingsRouteImport } from './routes/api/admin/bookings'
import { Route as ApiAdminEnquiriesRouteImport } from './routes/api/admin/enquiries'
import { Route as ApiAdminTripsRouteImport } from './routes/api/admin/trips'
import { Route as ApiTripsTripIdRouteImport } from './routes/api/trips/$tripId'
import { Route as AdminTripsTripIdEditRouteImport } from './routes/admin.trips.$tripId.edit'
import { Route as ApiAdminBookingsBookingIdRouteImport } from './routes/api/admin/bookings/$bookingId'
import { Route as ApiAdminEnquiresEnquiryIdRouteImport } from './routes/api/admin/enquires/$enquiryId'
import { Route as ApiAdminTripsTripIdRouteImport } from './routes/api/admin/trips/$tripId'
import { Route as ApiBookingBookingIdPaymentScreenshotRouteImport } from './routes/api/booking/$bookingId.payment-screenshot'
import { Route as ApiTripsTripIdImagesRouteImport } from './routes/api/trips/$tripId.images'
import { Route as ApiTripsTripIdItineraryRouteImport } from './routes/api/trips/$tripId.itinerary'
import { Route as ApiAdminBookingsBookingIdPaymentScreenshotRouteImport } from './routes/api/admin/bookings/$bookingId.payment-screenshot'
import { Route as ApiTripsTripIdImagesImageIdRouteImport } from './routes/api/trips/$tripId.images.$imageId'
import { Route as ApiTripsTripIdItineraryItineraryIdRouteImport } from './routes/api/trips/$tripId.itinerary.$itineraryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TripDetailRoute = TripDetailRouteImport.update({
  id: '/trip-detail',
  path: '/trip-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/admin/trips',
  path: '/admin/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingRoute = ApiBookingRouteImport.update({
  id: '/api/booking',
  path: '/api/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnquiriesRoute = ApiEnquiriesRouteImport.update({
  id: '/api/enquiries',
  path: '/api/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyBookingsRoute = ApiMyBookingsRouteImport.update({
  id: '/api/my-bookings',
  path: '/api/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripsRoute = ApiTripsRouteImport.update({
  id: '/api/trips',
  path: '/api/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/dashboard/bookings',
  path: '/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTripsIndexRoute = AdminTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTripsRoute,
} as any)
const AdminTripsNewRoute = AdminTripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTripsRoute,
} as any)
const ApiAdminBookingsRoute = ApiAdminBookingsRouteImport.update({
  id: '/api/admin/bookings',
  path: '/api/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEnquiriesRoute = ApiAdminEnquiriesRouteImport.update({
  id: '/api/admin/enquiries',
  path: '/api/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTripsRoute = ApiAdminTripsRouteImport.update({
  id: '/api/admin/trips',
  path: '/api/admin/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripsTripIdRoute = ApiTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => ApiTripsRoute,
} as any)
const AdminTripsTripIdEditRoute = AdminTripsTripIdEditRouteImport.update({
  id: '/$tripId/edit',
  path: '/$tripId/edit',
  getParentRoute: () => AdminTripsRoute,
} as any)
const ApiAdminBookingsBookingIdRoute =
  ApiAdminBookingsBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => ApiAdminBookingsRoute,
  } as any)
const ApiAdminEnquiresEnquiryIdRoute =
  ApiAdminEnquiresEnquiryIdRouteImport.update({
    id: '/api/admin/enquires/$enquiryId',
    path: '/api/admin/enquires/$enquiryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTripsTripIdRoute = ApiAdminTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => ApiAdminTripsRoute,
} as any)
const ApiBookingBookingIdPaymentScreenshotRoute =
  ApiBookingBookingIdPaymentScreenshotRouteImport.update({
    id: '/$bookingId/payment-screenshot',
    path: '/$bookingId/payment-screenshot',
    getParentRoute: () => ApiBookingRoute,
  } as any)
const ApiTripsTripIdImagesRoute = ApiTripsTripIdImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => ApiTripsTripIdRoute,
} as any)
const ApiTripsTripIdItineraryRoute = ApiTripsTripIdItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => ApiTripsTripIdRoute,
} as any)
const ApiAdminBookingsBookingIdPaymentScreenshotRoute =
  ApiAdminBookingsBookingIdPaymentScreenshotRouteImport.update({
    id: '/payment-screenshot',
    path: '/payment-screenshot',
    getParentRoute: () => ApiAdminBookingsBookingIdRoute,
  } as any)
const ApiTripsTripIdImagesImageIdRoute =
  ApiTripsTripIdImagesImageIdRouteImport.update({
    id: '/$imageId',
    path: '/$imageId',
    getParentRoute: () => ApiTripsTripIdImagesRoute,
  } as any)
const ApiTripsTripIdItineraryItineraryIdRoute =
  ApiTripsTripIdItineraryItineraryIdRouteImport.update({
    id: '/$itineraryId',
    path: '/$itineraryId',
    getParentRoute: () => ApiTripsTripIdItineraryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trip-detail': typeof TripDetailRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/api/booking': typeof ApiBookingRouteWithChildren
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/api/my-bookings': typeof ApiMyBookingsRoute
  '/api/trips': typeof ApiTripsRouteWithChildren
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRouteWithChildren
  '/api/admin/enquiries': typeof ApiAdminEnquiriesRoute
  '/api/admin/trips': typeof ApiAdminTripsRouteWithChildren
  '/api/trips/$tripId': typeof ApiTripsTripIdRouteWithChildren
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/admin/trips/$tripId/edit': typeof AdminTripsTripIdEditRoute
  '/api/admin/bookings/$bookingId': typeof ApiAdminBookingsBookingIdRouteWithChildren
  '/api/admin/enquires/$enquiryId': typeof ApiAdminEnquiresEnquiryIdRoute
  '/api/admin/trips/$tripId': typeof ApiAdminTripsTripIdRoute
  '/api/booking/$bookingId/payment-screenshot': typeof ApiBookingBookingIdPaymentScreenshotRoute
  '/api/trips/$tripId/images': typeof ApiTripsTripIdImagesRouteWithChildren
  '/api/trips/$tripId/itinerary': typeof ApiTripsTripIdItineraryRouteWithChildren
  '/api/admin/bookings/$bookingId/payment-screenshot': typeof ApiAdminBookingsBookingIdPaymentScreenshotRoute
  '/api/trips/$tripId/images/$imageId': typeof ApiTripsTripIdImagesImageIdRoute
  '/api/trips/$tripId/itinerary/$itineraryId': typeof ApiTripsTripIdItineraryItineraryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trip-detail': typeof TripDetailRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/booking': typeof ApiBookingRouteWithChildren
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/api/my-bookings': typeof ApiMyBookingsRoute
  '/api/trips': typeof ApiTripsRouteWithChildren
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRouteWithChildren
  '/api/admin/enquiries': typeof ApiAdminEnquiriesRoute
  '/api/admin/trips': typeof ApiAdminTripsRouteWithChildren
  '/api/trips/$tripId': typeof ApiTripsTripIdRouteWithChildren
  '/admin/trips': typeof AdminTripsIndexRoute
  '/admin/trips/$tripId/edit': typeof AdminTripsTripIdEditRoute
  '/api/admin/bookings/$bookingId': typeof ApiAdminBookingsBookingIdRouteWithChildren
  '/api/admin/enquires/$enquiryId': typeof ApiAdminEnquiresEnquiryIdRoute
  '/api/admin/trips/$tripId': typeof ApiAdminTripsTripIdRoute
  '/api/booking/$bookingId/payment-screenshot': typeof ApiBookingBookingIdPaymentScreenshotRoute
  '/api/trips/$tripId/images': typeof ApiTripsTripIdImagesRouteWithChildren
  '/api/trips/$tripId/itinerary': typeof ApiTripsTripIdItineraryRouteWithChildren
  '/api/admin/bookings/$bookingId/payment-screenshot': typeof ApiAdminBookingsBookingIdPaymentScreenshotRoute
  '/api/trips/$tripId/images/$imageId': typeof ApiTripsTripIdImagesImageIdRoute
  '/api/trips/$tripId/itinerary/$itineraryId': typeof ApiTripsTripIdItineraryItineraryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trip-detail': typeof TripDetailRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/api/booking': typeof ApiBookingRouteWithChildren
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/api/my-bookings': typeof ApiMyBookingsRoute
  '/api/trips': typeof ApiTripsRouteWithChildren
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRouteWithChildren
  '/api/admin/enquiries': typeof ApiAdminEnquiriesRoute
  '/api/admin/trips': typeof ApiAdminTripsRouteWithChildren
  '/api/trips/$tripId': typeof ApiTripsTripIdRouteWithChildren
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/admin/trips/$tripId/edit': typeof AdminTripsTripIdEditRoute
  '/api/admin/bookings/$bookingId': typeof ApiAdminBookingsBookingIdRouteWithChildren
  '/api/admin/enquires/$enquiryId': typeof ApiAdminEnquiresEnquiryIdRoute
  '/api/admin/trips/$tripId': typeof ApiAdminTripsTripIdRoute
  '/api/booking/$bookingId/payment-screenshot': typeof ApiBookingBookingIdPaymentScreenshotRoute
  '/api/trips/$tripId/images': typeof ApiTripsTripIdImagesRouteWithChildren
  '/api/trips/$tripId/itinerary': typeof ApiTripsTripIdItineraryRouteWithChildren
  '/api/admin/bookings/$bookingId/payment-screenshot': typeof ApiAdminBookingsBookingIdPaymentScreenshotRoute
  '/api/trips/$tripId/images/$imageId': typeof ApiTripsTripIdImagesImageIdRoute
  '/api/trips/$tripId/itinerary/$itineraryId': typeof ApiTripsTripIdItineraryItineraryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/contact'
    | '/login'
    | '/privacy-policy'
    | '/signup'
    | '/terms'
    | '/trip-detail'
    | '/trips'
    | '/admin/login'
    | '/admin/trips'
    | '/api/booking'
    | '/api/enquiries'
    | '/api/my-bookings'
    | '/api/trips'
    | '/dashboard/bookings'
    | '/admin/trips/new'
    | '/api/admin/bookings'
    | '/api/admin/enquiries'
    | '/api/admin/trips'
    | '/api/trips/$tripId'
    | '/admin/trips/'
    | '/admin/trips/$tripId/edit'
    | '/api/admin/bookings/$bookingId'
    | '/api/admin/enquires/$enquiryId'
    | '/api/admin/trips/$tripId'
    | '/api/booking/$bookingId/payment-screenshot'
    | '/api/trips/$tripId/images'
    | '/api/trips/$tripId/itinerary'
    | '/api/admin/bookings/$bookingId/payment-screenshot'
    | '/api/trips/$tripId/images/$imageId'
    | '/api/trips/$tripId/itinerary/$itineraryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/contact'
    | '/login'
    | '/privacy-policy'
    | '/signup'
    | '/terms'
    | '/trip-detail'
    | '/trips'
    | '/admin/login'
    | '/api/booking'
    | '/api/enquiries'
    | '/api/my-bookings'
    | '/api/trips'
    | '/dashboard/bookings'
    | '/admin/trips/new'
    | '/api/admin/bookings'
    | '/api/admin/enquiries'
    | '/api/admin/trips'
    | '/api/trips/$tripId'
    | '/admin/trips'
    | '/admin/trips/$tripId/edit'
    | '/api/admin/bookings/$bookingId'
    | '/api/admin/enquires/$enquiryId'
    | '/api/admin/trips/$tripId'
    | '/api/booking/$bookingId/payment-screenshot'
    | '/api/trips/$tripId/images'
    | '/api/trips/$tripId/itinerary'
    | '/api/admin/bookings/$bookingId/payment-screenshot'
    | '/api/trips/$tripId/images/$imageId'
    | '/api/trips/$tripId/itinerary/$itineraryId'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/contact'
    | '/login'
    | '/privacy-policy'
    | '/signup'
    | '/terms'
    | '/trip-detail'
    | '/trips'
    | '/admin/login'
    | '/admin/trips'
    | '/api/booking'
    | '/api/enquiries'
    | '/api/my-bookings'
    | '/api/trips'
    | '/dashboard/bookings'
    | '/admin/trips/new'
    | '/api/admin/bookings'
    | '/api/admin/enquiries'
    | '/api/admin/trips'
    | '/api/trips/$tripId'
    | '/admin/trips/'
    | '/admin/trips/$tripId/edit'
    | '/api/admin/bookings/$bookingId'
    | '/api/admin/enquires/$enquiryId'
    | '/api/admin/trips/$tripId'
    | '/api/booking/$bookingId/payment-screenshot'
    | '/api/trips/$tripId/images'
    | '/api/trips/$tripId/itinerary'
    | '/api/admin/bookings/$bookingId/payment-screenshot'
    | '/api/trips/$tripId/images/$imageId'
    | '/api/trips/$tripId/itinerary/$itineraryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TripDetailRoute: typeof TripDetailRoute
  TripsRoute: typeof TripsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTripsRoute: typeof AdminTripsRouteWithChildren
  ApiBookingRoute: typeof ApiBookingRouteWithChildren
  ApiEnquiriesRoute: typeof ApiEnquiriesRoute
  ApiMyBookingsRoute: typeof ApiMyBookingsRoute
  ApiTripsRoute: typeof ApiTripsRouteWithChildren
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  ApiAdminBookingsRoute: typeof ApiAdminBookingsRouteWithChildren
  ApiAdminEnquiriesRoute: typeof ApiAdminEnquiriesRoute
  ApiAdminTripsRoute: typeof ApiAdminTripsRouteWithChildren
  ApiAdminEnquiresEnquiryIdRoute: typeof ApiAdminEnquiresEnquiryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip-detail': {
      id: '/trip-detail'
      path: '/trip-detail'
      fullPath: '/trip-detail'
      preLoaderRoute: typeof TripDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/admin/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking': {
      id: '/api/booking'
      path: '/api/booking'
      fullPath: '/api/booking'
      preLoaderRoute: typeof ApiBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enquiries': {
      id: '/api/enquiries'
      path: '/api/enquiries'
      fullPath: '/api/enquiries'
      preLoaderRoute: typeof ApiEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my-bookings': {
      id: '/api/my-bookings'
      path: '/api/my-bookings'
      fullPath: '/api/my-bookings'
      preLoaderRoute: typeof ApiMyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trips': {
      id: '/api/trips'
      path: '/api/trips'
      fullPath: '/api/trips'
      preLoaderRoute: typeof ApiTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trips/': {
      id: '/admin/trips/'
      path: '/'
      fullPath: '/admin/trips/'
      preLoaderRoute: typeof AdminTripsIndexRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/admin/trips/new': {
      id: '/admin/trips/new'
      path: '/new'
      fullPath: '/admin/trips/new'
      preLoaderRoute: typeof AdminTripsNewRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/api/admin/bookings': {
      id: '/api/admin/bookings'
      path: '/api/admin/bookings'
      fullPath: '/api/admin/bookings'
      preLoaderRoute: typeof ApiAdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/enquiries': {
      id: '/api/admin/enquiries'
      path: '/api/admin/enquiries'
      fullPath: '/api/admin/enquiries'
      preLoaderRoute: typeof ApiAdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/trips': {
      id: '/api/admin/trips'
      path: '/api/admin/trips'
      fullPath: '/api/admin/trips'
      preLoaderRoute: typeof ApiAdminTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trips/$tripId': {
      id: '/api/trips/$tripId'
      path: '/$tripId'
      fullPath: '/api/trips/$tripId'
      preLoaderRoute: typeof ApiTripsTripIdRouteImport
      parentRoute: typeof ApiTripsRoute
    }
    '/admin/trips/$tripId/edit': {
      id: '/admin/trips/$tripId/edit'
      path: '/$tripId/edit'
      fullPath: '/admin/trips/$tripId/edit'
      preLoaderRoute: typeof AdminTripsTripIdEditRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/api/admin/bookings/$bookingId': {
      id: '/api/admin/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/api/admin/bookings/$bookingId'
      preLoaderRoute: typeof ApiAdminBookingsBookingIdRouteImport
      parentRoute: typeof ApiAdminBookingsRoute
    }
    '/api/admin/enquires/$enquiryId': {
      id: '/api/admin/enquires/$enquiryId'
      path: '/api/admin/enquires/$enquiryId'
      fullPath: '/api/admin/enquires/$enquiryId'
      preLoaderRoute: typeof ApiAdminEnquiresEnquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/trips/$tripId': {
      id: '/api/admin/trips/$tripId'
      path: '/$tripId'
      fullPath: '/api/admin/trips/$tripId'
      preLoaderRoute: typeof ApiAdminTripsTripIdRouteImport
      parentRoute: typeof ApiAdminTripsRoute
    }
    '/api/booking/$bookingId/payment-screenshot': {
      id: '/api/booking/$bookingId/payment-screenshot'
      path: '/$bookingId/payment-screenshot'
      fullPath: '/api/booking/$bookingId/payment-screenshot'
      preLoaderRoute: typeof ApiBookingBookingIdPaymentScreenshotRouteImport
      parentRoute: typeof ApiBookingRoute
    }
    '/api/trips/$tripId/images': {
      id: '/api/trips/$tripId/images'
      path: '/images'
      fullPath: '/api/trips/$tripId/images'
      preLoaderRoute: typeof ApiTripsTripIdImagesRouteImport
      parentRoute: typeof ApiTripsTripIdRoute
    }
    '/api/trips/$tripId/itinerary': {
      id: '/api/trips/$tripId/itinerary'
      path: '/itinerary'
      fullPath: '/api/trips/$tripId/itinerary'
      preLoaderRoute: typeof ApiTripsTripIdItineraryRouteImport
      parentRoute: typeof ApiTripsTripIdRoute
    }
    '/api/admin/bookings/$bookingId/payment-screenshot': {
      id: '/api/admin/bookings/$bookingId/payment-screenshot'
      path: '/payment-screenshot'
      fullPath: '/api/admin/bookings/$bookingId/payment-screenshot'
      preLoaderRoute: typeof ApiAdminBookingsBookingIdPaymentScreenshotRouteImport
      parentRoute: typeof ApiAdminBookingsBookingIdRoute
    }
    '/api/trips/$tripId/images/$imageId': {
      id: '/api/trips/$tripId/images/$imageId'
      path: '/$imageId'
      fullPath: '/api/trips/$tripId/images/$imageId'
      preLoaderRoute: typeof ApiTripsTripIdImagesImageIdRouteImport
      parentRoute: typeof ApiTripsTripIdImagesRoute
    }
    '/api/trips/$tripId/itinerary/$itineraryId': {
      id: '/api/trips/$tripId/itinerary/$itineraryId'
      path: '/$itineraryId'
      fullPath: '/api/trips/$tripId/itinerary/$itineraryId'
      preLoaderRoute: typeof ApiTripsTripIdItineraryItineraryIdRouteImport
      parentRoute: typeof ApiTripsTripIdItineraryRoute
    }
  }
}

interface AdminTripsRouteChildren {
  AdminTripsNewRoute: typeof AdminTripsNewRoute
  AdminTripsIndexRoute: typeof AdminTripsIndexRoute
  AdminTripsTripIdEditRoute: typeof AdminTripsTripIdEditRoute
}

const AdminTripsRouteChildren: AdminTripsRouteChildren = {
  AdminTripsNewRoute: AdminTripsNewRoute,
  AdminTripsIndexRoute: AdminTripsIndexRoute,
  AdminTripsTripIdEditRoute: AdminTripsTripIdEditRoute,
}

const AdminTripsRouteWithChildren = AdminTripsRoute._addFileChildren(
  AdminTripsRouteChildren,
)

interface ApiBookingRouteChildren {
  ApiBookingBookingIdPaymentScreenshotRoute: typeof ApiBookingBookingIdPaymentScreenshotRoute
}

const ApiBookingRouteChildren: ApiBookingRouteChildren = {
  ApiBookingBookingIdPaymentScreenshotRoute:
    ApiBookingBookingIdPaymentScreenshotRoute,
}

const ApiBookingRouteWithChildren = ApiBookingRoute._addFileChildren(
  ApiBookingRouteChildren,
)

interface ApiTripsTripIdImagesRouteChildren {
  ApiTripsTripIdImagesImageIdRoute: typeof ApiTripsTripIdImagesImageIdRoute
}

const ApiTripsTripIdImagesRouteChildren: ApiTripsTripIdImagesRouteChildren = {
  ApiTripsTripIdImagesImageIdRoute: ApiTripsTripIdImagesImageIdRoute,
}

const ApiTripsTripIdImagesRouteWithChildren =
  ApiTripsTripIdImagesRoute._addFileChildren(ApiTripsTripIdImagesRouteChildren)

interface ApiTripsTripIdItineraryRouteChildren {
  ApiTripsTripIdItineraryItineraryIdRoute: typeof ApiTripsTripIdItineraryItineraryIdRoute
}

const ApiTripsTripIdItineraryRouteChildren: ApiTripsTripIdItineraryRouteChildren =
  {
    ApiTripsTripIdItineraryItineraryIdRoute:
      ApiTripsTripIdItineraryItineraryIdRoute,
  }

const ApiTripsTripIdItineraryRouteWithChildren =
  ApiTripsTripIdItineraryRoute._addFileChildren(
    ApiTripsTripIdItineraryRouteChildren,
  )

interface ApiTripsTripIdRouteChildren {
  ApiTripsTripIdImagesRoute: typeof ApiTripsTripIdImagesRouteWithChildren
  ApiTripsTripIdItineraryRoute: typeof ApiTripsTripIdItineraryRouteWithChildren
}

const ApiTripsTripIdRouteChildren: ApiTripsTripIdRouteChildren = {
  ApiTripsTripIdImagesRoute: ApiTripsTripIdImagesRouteWithChildren,
  ApiTripsTripIdItineraryRoute: ApiTripsTripIdItineraryRouteWithChildren,
}

const ApiTripsTripIdRouteWithChildren = ApiTripsTripIdRoute._addFileChildren(
  ApiTripsTripIdRouteChildren,
)

interface ApiTripsRouteChildren {
  ApiTripsTripIdRoute: typeof ApiTripsTripIdRouteWithChildren
}

const ApiTripsRouteChildren: ApiTripsRouteChildren = {
  ApiTripsTripIdRoute: ApiTripsTripIdRouteWithChildren,
}

const ApiTripsRouteWithChildren = ApiTripsRoute._addFileChildren(
  ApiTripsRouteChildren,
)

interface ApiAdminBookingsBookingIdRouteChildren {
  ApiAdminBookingsBookingIdPaymentScreenshotRoute: typeof ApiAdminBookingsBookingIdPaymentScreenshotRoute
}

const ApiAdminBookingsBookingIdRouteChildren: ApiAdminBookingsBookingIdRouteChildren =
  {
    ApiAdminBookingsBookingIdPaymentScreenshotRoute:
      ApiAdminBookingsBookingIdPaymentScreenshotRoute,
  }

const ApiAdminBookingsBookingIdRouteWithChildren =
  ApiAdminBookingsBookingIdRoute._addFileChildren(
    ApiAdminBookingsBookingIdRouteChildren,
  )

interface ApiAdminBookingsRouteChildren {
  ApiAdminBookingsBookingIdRoute: typeof ApiAdminBookingsBookingIdRouteWithChildren
}

const ApiAdminBookingsRouteChildren: ApiAdminBookingsRouteChildren = {
  ApiAdminBookingsBookingIdRoute: ApiAdminBookingsBookingIdRouteWithChildren,
}

const ApiAdminBookingsRouteWithChildren =
  ApiAdminBookingsRoute._addFileChildren(ApiAdminBookingsRouteChildren)

interface ApiAdminTripsRouteChildren {
  ApiAdminTripsTripIdRoute: typeof ApiAdminTripsTripIdRoute
}

const ApiAdminTripsRouteChildren: ApiAdminTripsRouteChildren = {
  ApiAdminTripsTripIdRoute: ApiAdminTripsTripIdRoute,
}

const ApiAdminTripsRouteWithChildren = ApiAdminTripsRoute._addFileChildren(
  ApiAdminTripsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TripDetailRoute: TripDetailRoute,
  TripsRoute: TripsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTripsRoute: AdminTripsRouteWithChildren,
  ApiBookingRoute: ApiBookingRouteWithChildren,
  ApiEnquiriesRoute: ApiEnquiriesRoute,
  ApiMyBookingsRoute: ApiMyBookingsRoute,
  ApiTripsRoute: ApiTripsRouteWithChildren,
  DashboardBookingsRoute: DashboardBookingsRoute,
  ApiAdminBookingsRoute: ApiAdminBookingsRouteWithChildren,
  ApiAdminEnquiriesRoute: ApiAdminEnquiriesRoute,
  ApiAdminTripsRoute: ApiAdminTripsRouteWithChildren,
  ApiAdminEnquiresEnquiryIdRoute: ApiAdminEnquiresEnquiryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
